<?xml version="1.0"?>
<package format="3">
  <name>car_nav</name>
  <version>0.0.1</version>
  <description>Custom global planner (Dijkstra) and nav utilities</description>

  <maintainer email="you@example.com">zzz</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>nav2_core</depend>
  <depend>nav2_costmap_2d</depend>
  <depend>nav2_util</depend>
  <depend>pluginlib</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>sensor_msgs</depend>
  <exec_depend>slam_toolbox</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>


  <export>
    <pluginlib plugin="${prefix}/planner_config/plan.xml"/>
    <build_type>ament_cmake</build_type>
  </export>
</package>
